### ISSUE TITLE
Graphana Dashboard Showing only One Example-storage-cluster

### ISSUE THREAD

**Issue by viju2008** [oracle/coherence-operator#460]
Hello,

I have created two clusters in the same namespace and followed the steps in the Deployment and AutoScaler example.

Prometheus is showing metrics for example-cluster. However not showing for the second cluster.

Is there any reconfiguration to be applied. I tried applying the graphana related yamls again . However it is not showing the second cluster.

Should i create a new query with Prometheus to see the dashboard.

**Comment by thegridman** [comment]
This is due to a difference in Prometheus metric names being produced by the different Coherence clusters that you are running.
Coherence has two formats of metric names, one is the default format which has been used since metrics were first introduced into Coherence in 12.4.1 where for example the cluster size metric name is `vendor:coherence_cluster_size` the second format is compatible with the format used by Microprofile metrics where the metric name for cluster size is `vendor_Coherence_Cluster_Size`
